import { createFileRoute, Link } from "@tanstack/react-router";

import { AppShell } from "@/components/soc/AppShell";
import {
  HumanGate,
  PageHeader,
  Panel,
  Pill,
  StatCard,
  StatusPill,
  formatMinutes,
} from "@/components/soc/primitives";
import { responseTasks } from "@/lib/soc/derive";

export const Route = createFileRoute("/tasks")({
  head: () => ({
    meta: [
      { title: "Response Tasks — Security Incident Automation Lab" },
      {
        name: "description",
        content:
          "Synthetic response task board showing which steps were generated by simulated playbooks and which are blocked pending documented human approval.",
      },
      { property: "og:title", content: "Response Tasks" },
      {
        property: "og:description",
        content: "Task board separating automated steps from human-approval gates.",
      },
    ],
  }),
  component: Tasks,
});

function Tasks() {
  const groups = [...new Set(responseTasks.map((t) => t.assignmentGroup))];
  const automated = responseTasks.filter((t) => t.automated).length;
  const awaiting = responseTasks.filter(
    (t) => t.requiresApproval && t.status !== "complete",
  ).length;
  const complete = responseTasks.filter((t) => t.status === "complete").length;

  return (
    <AppShell>
      <PageHeader
        eyebrow="Response Tasks"
        title="Work assigned across the response"
        description="Tasks are attributed to an assignment group derived from the routing rules. Tasks marked automated were created by a simulated playbook run, not executed against any real system."
      />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Total tasks" value={responseTasks.length} />
        <StatCard label="Playbook-generated" value={automated} tone="primary" />
        <StatCard label="Awaiting approval" value={awaiting} tone="critical" />
        <StatCard label="Complete" value={complete} tone="success" />
      </div>

      {awaiting > 0 && (
        <HumanGate
          reason={`${awaiting} task(s) are held pending explicit human approval. The demo never advances them automatically.`}
        />
      )}

      {groups.map((g) => (
        <Panel key={g} title={g}>
          <ul className="space-y-2">
            {responseTasks
              .filter((t) => t.assignmentGroup === g)
              .map((t) => (
                <li
                  key={t.id}
                  className="flex flex-wrap items-center gap-2 border-b border-border/50 pb-2 last:border-0"
                >
                  <StatusPill status={t.status} />
                  <span className="min-w-0 flex-1 text-sm text-foreground">{t.title}</span>
                  {t.automated && <Pill tone="info">automated</Pill>}
                  {t.requiresApproval && <Pill tone="critical">approval required</Pill>}
                  <span className="font-mono text-[11px] text-muted-foreground">
                    due {formatMinutes(t.dueInMinutes)}
                  </span>
                  <Link
                    to="/incidents/$id"
                    params={{ id: t.incidentId }}
                    className="font-mono text-xs text-primary hover:underline"
                  >
                    {t.incidentId}
                  </Link>
                </li>
              ))}
          </ul>
        </Panel>
      ))}
    </AppShell>
  );
}
